device:
  CUDA_VISIBLE_DEVICES: '2,3'

data:
  CUB200:
    data_root: 'datasets/CUB_200_2011'
    batch_size: 128
    num_workers: 10
    shuffle: True
    augmentations:
      train:
        Resize:
          size: 800
        RandomCrop:
          size: 700
        ColorJitter:
          contrast: 0.5
        Normalize:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      test:
        Resize:
          size: 800
        TenCrop:
          size: 700
        Normalize:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]

model:
  Attention:
    AttentionModule:
      sample_mode:
        Interpolate:
          name: 'F.interpolate'
          sample_params:
              size: 96
              mode: bilinear
              align_corners: True
      num_verts_out: 1024
      in_channels: [3, 64, 64]
      out_channels: [64, 64, 1]
      bias: True
      use_mask: True
      mask_size: 12
      norm: Min-Max
  TaskNetwork:
    ResNet:
      pretrained: True
  Warper:
    SpatialWarper:
      delta: 0.72
      inv_eps: 100
      num_verts: 1024
      task_img_size: 224

optimizer:
  SGD:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001
  scheduler:
    step_size: 50
    gamma: 0.1
  num_epochs: 300

random_seed: 2
